// fbsTeams.ts

export const fbsTeams = [
    "Air Force",
    "Akron",
    "Alabama",
    "Appalachian State",
    "Arizona",
    "Arizona State",
    "Arkansas",
    "Arkansas State",
    "Army",
    "Auburn",
    "Ball State",
    "Baylor",
    "Boise State",
    "Boston College",
    "Bowling Green",
    "Buffalo",
    "BYU",
    "California",
    "Central Michigan",
    "Charlotte",
    "Cincinnati",
    "Clemson",
    "Coastal Carolina",
    "Colorado",
    "Colorado State",
    "Duke",
    "East Carolina",
    "Eastern Michigan",
    "FIU",
    "Florida",
    "Florida Atlantic",
    "Florida State",
    "Fresno State",
    "Georgia",
    "Georgia Southern",
    "Georgia State",
    "Georgia Tech",
    "Hawaii",
    "Houston",
    "Illinois",
    "Indiana",
    "Iowa",
    "Iowa State",
    "Jacksonville State",
    "James Madison",
    "Kansas",
    "Kansas State",
    "Kennesaw State",
    "Kent State",
    "Kentucky",
    "Liberty",
    "Louisiana",
    "Louisiana Tech",
    "Louisiana-Monroe",
    "Louisville",
    "LSU",
    "Marshall",
    "Maryland",
    "Memphis",
    "Miami (FL)",
    "Miami (OH)",
    "Michigan",
    "Michigan State",
    "Middle Tennessee",
    "Minnesota",
    "Mississippi State",
    "Missouri",
    "Navy",
    "NC State",
    "Nebraska",
    "Nevada",
    "New Mexico",
    "New Mexico State",
    "North Carolina",
    "North Texas",
    "Northern Illinois",
    "Northwestern",
    "Notre Dame",
    "Ohio",
    "Ohio State",
    "Oklahoma",
    "Oklahoma State",
    "Old Dominion",
    "Ole Miss",
    "Oregon",
    "Oregon State",
    "Penn State",
    "Pittsburgh",
    "Purdue",
    "Rice",
    "Rutgers",
    "Sam Houston",
    "San Diego State",
    "San Jose State",
    "SMU",
    "South Alabama",
    "South Carolina",
    "South Florida",
    "Southern Miss",
    "Stanford",
    "Syracuse",
    "TCU",
    "Temple",
    "Tennessee",
    "Texas",
    "Texas A&M",
    "Texas State",
    "Texas Tech",
    "Toledo",
    "Troy",
    "Tulane",
    "Tulsa",
    "UAB",
    "UCF",
    "UCLA",
    "UConn",
    "UMass",
    "UNLV",
    "USC",
    "UTEP",
    "UTSA",
    "Utah",
    "Utah State",
    "Vanderbilt",
    "Virginia",
    "Virginia Tech",
    "Wake Forest",
    "Washington",
    "Washington State",
    "West Virginia",
    "Western Kentucky",
    "Western Michigan",
    "Wisconsin",
    "Wyoming",
    "BYE"
  ];